package lexer;

/**
 * This file is automatically generated
 * - it contains the enumeration of all of the tokens
 */
public enum Tokens {
  BogusToken, Program, Int, BOOLean, If,
  Then, Else, While, Function, Return,
  Identifier, INTeger, LeftBrace, RightBrace, LeftParen,
  RightParen, Comma, Assign, Equal, NotEqual,
  Less, LessEqual, Plus, Minus, Or,
  And, Multiply, Divide, Comment, Greater,
  GreaterEqual, LeftBracket, RightBracket, Modulo, Arrow,
  Unless, Select, StringType, StringLit, HexType,
  HexLit, EOF
}

